### ISSUE TITLE
Add Original Audio

### ISSUE THREAD

**Issue by MatteCrystal** [indigocalifornia/mvgen#3]
Could someone add the option to output an mp3 with the original audio of the output video?

Also an option to include it automatically in the final video merged with the music as well as an option to just render the output video with the original audio and no music at all would also be great.

**Comment by indigocalifornia** [comment]
This should be straightforward, if we only want to keep original audio. I assume this is the audio from the videos, so the audio will change every scene change.

If we want to mix, then need to see how ffmpeg handles audio mixing.

**Comment by indigocalifornia** [comment]
Has been added https://github.com/indigocalifornia/pmvc/commit/1f140ee4a7f20100aaf6c38963bed0809bb83259
